// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVhAqaC5v8QcsBwUB4tE4DSP7WhA3y0ls',
    appId: '1:157165863355:web:d2f3d3bb33c8098abcc49e',
    messagingSenderId: '157165863355',
    projectId: 'ficha-estoque',
    authDomain: 'ficha-estoque.firebaseapp.com',
    storageBucket: 'ficha-estoque.appspot.com',
    measurementId: 'G-06LM60623W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVUOwT_Lwth_ClpC4f5Y5J_qESHR4Rf6s',
    appId: '1:157165863355:android:93783037f152e282bcc49e',
    messagingSenderId: '157165863355',
    projectId: 'ficha-estoque',
    storageBucket: 'ficha-estoque.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAghD0qYaiSoHg-1xtIXiTxjpW0zyZjBDQ',
    appId: '1:157165863355:ios:29e9b0acbeeb2630bcc49e',
    messagingSenderId: '157165863355',
    projectId: 'ficha-estoque',
    storageBucket: 'ficha-estoque.appspot.com',
    iosClientId: '157165863355-ko1qrftrmsub5o2gn43ncf5feslbvdq9.apps.googleusercontent.com',
    iosBundleId: 'com.example.fichaEstoque',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAghD0qYaiSoHg-1xtIXiTxjpW0zyZjBDQ',
    appId: '1:157165863355:ios:29e9b0acbeeb2630bcc49e',
    messagingSenderId: '157165863355',
    projectId: 'ficha-estoque',
    storageBucket: 'ficha-estoque.appspot.com',
    iosClientId: '157165863355-ko1qrftrmsub5o2gn43ncf5feslbvdq9.apps.googleusercontent.com',
    iosBundleId: 'com.example.fichaEstoque',
  );
}
